apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-app-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  ConnectionStrings__DefaultConnection: {{ .Values.secret.connectionString | quote }}
  MainConfiguration__GeocodingApiKey: {{ .Values.secret.geocodingApiKey | quote }}
  MainConfiguration__OpenWeatherApiKey: {{ .Values.secret.openWeatherApiKey | quote }}
  MainConfiguration__TelegramBotToken: {{ .Values.secret.telegramBotToken | quote }}
  MainConfiguration__InternalApiKey: {{ .Values.secret.internalApiKey | quote }}
