apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-app-secret
type: Opaque
stringData:
  DB_PASSWORD: "admin"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=forecast;Username=postgres;Password=admin"
  MainConfiguration__GeocodingApiKey: "mock_geocoding_key"
  MainConfiguration__OpenWeatherApiKey: "mock_openweather_key"
  MainConfiguration__TelegramBotToken: "mock_telegram_token"
  MainConfiguration__InternalApiKey: "mock_internal_key"
